[package]
name = "ytp-simple"
version = "0.1.0"
edition = "2021"
authors = ["Steven Zimmerman"]
description = "A simple CLI tool"
license = "MIT"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0" 